spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/afisha?afishaSchema=afisha_schema
    driver-class-name: org.postgresql.Driver
server:
  port: 80

app:
  db:
    host: localhost
    port: 5432