spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    sql-format: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/users?currentSchema=user
    driver-class-name: org.postgresql.Driver
server:
  port: 82